import React,{useEffect,useLayoutEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {MotionClock,gazeCell} from '../../src/motion.ts';
import {noticeCopy} from '../../src/notice-copy.ts';
import {editorCaret} from './caret.ts';
import type {CallState} from '../../src/voice-call.ts';
import {ANIMATIONS,type Pose} from '../../src/model.ts';
import {RequestForm} from '../../src/notification-tray.tsx';
type Bridge={subscribe(fn:(value:any)=>void):()=>void;emit(value:unknown):void;focus():void;focusHost():Promise<{ok:boolean;error?:string}>;hitZones(value:unknown):void;drag(active:boolean,id:string):void;resize(geometry:{height:number;petTop:number}):void};
const bridge=(window as any).petDesktop as Bridge;
window.addEventListener('error',()=>bridge.emit({type:'native-error',error:'Floating pet renderer failed'}));
const originalMatchMedia=window.matchMedia.bind(window);
let latest:any=null;const subscribers=new Set<(value:any)=>void>();
bridge.subscribe(value=>{if(value.type==='snapshot')latest=value;for(const fn of subscribers)fn(value);});
const paths:Record<string,React.ReactNode>={mic:<><rect x="9" y="3" width="6" height="12" rx="3"/><path d="M5 10v2a7 7 0 0 0 14 0v-2M12 19v3M8 22h8"/></>,muted:<><path d="M9 9V6a3 3 0 0 1 6 0v6M5 10v2a7 7 0 0 0 12 5M12 19v3M8 22h8M3 3l18 18"/></>,hangup:<path d="M4 14c5-4 11-4 16 0v4l-5-1v-3M9 14v3l-5 1v-4"/>,voice:<><path d="M5 10v4M9 6v12M13 8v8M17 10v4"/></>,down:<path d="m6 9 6 6 6-6"/>,bell:<><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></>,plus:<path d="M12 5v14M5 12h14"/>,send:<path d="M12 19V5m-6 6 6-6 6 6"/>,close:<path d="m6 6 12 12M18 6 6 18"/>,reply:<><path d="m8 6-5 5 5 5"/><path d="M3 11h11a6 6 0 0 0 6-6"/></>,stop:<rect x="6" y="6" width="12" height="12" rx="2" fill="currentColor" stroke="none"/>,question:<><circle cx="12" cy="12" r="9"/><path d="M9 8a3 3 0 1 1 4 3c-1 1-1 2-1 3M12 17h.01"/></>};
function Icon({name}:{name:string}){if(name==='new')return <svg viewBox="0 0 20 20" aria-hidden="true"><path d="M8.16675 2.50127C8.53391 2.50127 8.83161 2.7992 8.83179 3.16631C8.83179 3.53358 8.53402 3.83135 8.16675 3.83135H5.83374C4.72836 3.83135 3.83197 4.72797 3.83179 5.8333V14.1663C3.83179 15.2718 4.72825 16.1683 5.83374 16.1683H14.1667C15.2722 16.1683 16.1687 15.2718 16.1687 14.1663V11.8333C16.1689 11.4662 16.4666 11.1683 16.8337 11.1683C17.2007 11.1684 17.4986 11.4663 17.4988 11.8333V14.1663C17.4988 16.0063 16.0068 17.4983 14.1667 17.4983H5.83374C3.99371 17.4983 2.50171 16.0063 2.50171 14.1663V5.8333C2.50189 3.99343 3.99382 2.50127 5.83374 2.50127H8.16675Z" fill="currentColor" stroke="none"/><path d="M13.4265 3.10381C14.3857 2.15908 15.9276 2.16466 16.8796 3.11651C17.8339 4.07106 17.8372 5.61827 16.8865 6.57647L11.7244 11.7786C11.3005 12.2058 10.7622 12.5027 10.1746 12.6321L7.78784 13.1565C7.20661 13.2842 6.6889 12.766 6.81714 12.1849L7.34253 9.80498C7.47294 9.21426 7.77197 8.67391 8.20288 8.24932L13.4265 3.10381ZM15.9392 4.05694C15.5038 3.62172 14.7988 3.61907 14.3601 4.05108L9.13647 9.19659C8.88861 9.44077 8.71644 9.75138 8.64136 10.0911L8.28979 11.6849L9.88843 11.3333C10.2265 11.2588 10.5362 11.0878 10.78 10.8421L15.9421 5.63897C16.3769 5.20075 16.3756 4.49352 15.9392 4.05694Z" fill="currentColor" stroke="none" fillRule="evenodd" clipRule="evenodd"/></svg>;if(name==='reply')return <svg viewBox="0 0 20 20" aria-hidden="true"><path d="M15.8 5.8v3.4c0 1.1-.6 1.7-1.7 1.7H4.4m3.1-3.3-3.2 3.2 3.2 3.2" strokeWidth="1.33"/></svg>;return <svg viewBox="0 0 24 24" aria-hidden="true">{paths[name]}</svg>;}
function NoticeCard({item,command,showRequest,t,drafts}:{item:any;command:(value:any)=>Promise<void>;showRequest:()=>void;t:(zh:string,en:string)=>string;drafts:Map<string,string>}){
 const key=item.id+':'+item.token,[expanded,setExpanded]=useState(false),[draft,setDraft]=useState(drafts.get(key)||''),[busy,setBusy]=useState(false),[error,setError]=useState(''),input=useRef<HTMLTextAreaElement>(null);
 const openReply=()=>{setExpanded(true);bridge.focus();};
 const send=async()=>{if(!draft.trim()||busy)return;setBusy(true);setError('');try{await command({type:'reply',id:item.id,token:item.token,text:draft});drafts.delete(key);setDraft('');setExpanded(false);}catch(cause){setError(cause instanceof Error?cause.message:String(cause));}finally{setBusy(false);}};
 useEffect(()=>{if(expanded)requestAnimationFrame(()=>input.current?.focus());},[expanded]);
 useEffect(()=>{const fixture=(value:any)=>{if(value.type!=='fixture-ui'||value.id!==item.id)return;if(value.action==='open-task')void openTask();else if(value.action==='reply')openReply();else if(value.action==='reply-text'){setDraft(value.text||'');drafts.set(key,value.text||'');}else if(value.action==='reply-send')void send();};subscribers.add(fixture);return()=>{subscribers.delete(fixture);};},[item.id,key,draft,busy]);
 const copy=noticeCopy(item,t);
 const openTask=async()=>{setError('');try{await command({type:'open',id:item.id,token:item.token});const result=await bridge.focusHost();if(!result.ok)setError(t('会话已切换，但未能将 DSH 窗口带到前台。','Task opened, but Windows did not bring DSH to the foreground.'));}catch(cause){setError(cause instanceof Error?cause.message:String(cause));}};
 return <article className={'notice '+(expanded?'is-expanded':'')} data-hit data-notice={item.id} data-phase={item.phase||item.pose}>
  <button className="dismiss" title={t('关闭提醒','Dismiss')} onClick={()=>void command({type:'dismiss',id:item.id,token:item.token}).catch(cause=>setError(String(cause)))}><Icon name="close"/></button>
  <div className="notice-header"><button className="notice-copy" onClick={()=>void openTask()}><strong>{item.pose==='review'?<span className="complete-mark">✓</span>:null}{item.title}</strong><span className={'notice-subtitle '+(copy.busy?'is-active':'')}>{copy.text}</span></button>
   <div className="notice-actions"><button className="round" aria-pressed={expanded} title={item.request?t('处理请求','Respond to request'):t('回复会话','Reply to conversation')} onClick={()=>item.request?showRequest():expanded&&draft.trim()?void send():openReply()}><Icon name={item.request?'question':'reply'}/></button>{item.pose==='running'?<button className="round" title={t('停止','Stop')} onClick={()=>void command({type:'stop',id:item.id,token:item.token}).catch(cause=>setError(String(cause)))}><Icon name="stop"/></button>:null}</div>
  </div>
  {expanded?<form className="follow-up" onSubmit={event=>{event.preventDefault();void send();}}><textarea ref={input} rows={1} maxLength={10000} value={draft} disabled={busy} aria-label={t('继续跟进','Follow up')} placeholder={t('继续跟进','Follow up')} onChange={event=>{setDraft(event.target.value);drafts.set(key,event.target.value);}} onKeyDown={event=>{if(event.key==='Escape')setExpanded(false);else if(event.key==='Enter'&&!event.shiftKey&&!event.nativeEvent.isComposing){event.preventDefault();void send();}}}/></form>:null}
  {error?<div className="reply-error" role="alert">{error}</div>:null}
 </article>;
}
function App(){
 const [state,setState]=useState<any>(latest),[collapsed,setCollapsed]=useState(false),[compose,setCompose]=useState(false),[draft,setDraft]=useState(''),[files,setFiles]=useState<string[]>([]),[error,setError]=useState(''),[voice,setVoice]=useState('idle'),[busy,setBusy]=useState(false),[menu,setMenu]=useState(false),[request,setRequest]=useState<any>(null),[transient,setTransient]=useState<Pose|null>(null),[hover,setHover]=useState(false),[cell,setCell]=useState({row:0,column:0,duration:1});
 const shell=useRef<HTMLDivElement>(null),pet=useRef<HTMLDivElement>(null),input=useRef<HTMLInputElement>(null),clock=useRef(new MotionClock()),dragging=useRef(false),pending=useRef(''),pixels=useRef<Uint8ClampedArray|null>(null),replies=useRef(new Map<string,{resolve:()=>void;reject:(cause:Error)=>void;timer:ReturnType<typeof setTimeout>}>());
 const [call,setCall]=useState<CallState>({phase:'off',active:false,muted:false,title:'',sessionId:null,heard:'',said:'',error:'',level:0});
 const [controls,setControls]=useState(false),[above,setAbove]=useState(false),[panelOffsetX,setPanelOffsetX]=useState(0);const hoverTimer=useRef<ReturnType<typeof setTimeout>>(),replyDrafts=useRef(new Map<string,string>());
 const captureId=useRef<number|null>(null),dragToken=useRef('');
 const endDrag=()=>{if(!dragging.current)return;dragging.current=false;bridge.drag(false,dragToken.current);setTransient(null);const id=captureId.current;captureId.current=null;try{if(id!==null&&pet.current?.hasPointerCapture(id))pet.current.releasePointerCapture(id);}catch{/* native capture was already released */}};
 const endDragRef=useRef(endDrag);endDragRef.current=endDrag;
 const foldRef=useRef(()=>{});
 const size=state?.config?.size||120,items=state?.notifications?.items||[],requestedPose=transient ?? (hover?'jumping':state?.notifications?.activity?.pose||'idle'),pose=(Object.hasOwn(ANIMATIONS,requestedPose)?requestedPose:'idle') as Pose;
 const chinese=!String(state?.language||'zh').startsWith('en'),t=(zh:string,en:string)=>chinese?zh:en;
 const action=(command:any)=>{const id=crypto.randomUUID();bridge.emit({type:'command',id,command});return id;};
 const answered=(command:any)=>new Promise<void>((resolve,reject)=>{const id=action(command),timer=setTimeout(()=>{replies.current.delete(id);reject(new Error(t('提交超时','Request timed out')));},30000);replies.current.set(id,{resolve,reject,timer});});
 const dismissComposer=()=>{setCompose(false);setMenu(false);setVoice('idle');action({type:'voice-cancel'});};
 const dismissRef=useRef(dismissComposer);dismissRef.current=dismissComposer;
 useEffect(()=>{const listener=(value:any)=>{
  if(value.type==='snapshot')setState(value);
  else if(value.type==='call-state')setCall(value.value);
  else if(value.type==='layout'){setAbove(!!value.above);setPanelOffsetX(value.panelOffsetX||0);}
  else if(value.type==='hover-region'){clearTimeout(hoverTimer.current);if(value.hover)setControls(true);else hoverTimer.current=setTimeout(()=>setControls(false),300);}
  else if(value.type==='window-blur'){endDragRef.current();dismissRef.current();}
  else if(value.type==='drag-ended'&&value.id===dragToken.current)endDragRef.current();
  else if(value.type==='drag-motion'){if(value.dx>=4)setTransient('running-right');else if(value.dx<=-4)setTransient('running-left');}
  else if(value.type==='composer'){setVoice(value.state||'idle');if(value.text)setDraft(old=>old+value.text);setError(typeof value.error==='string'?value.error:'');}
  else if(value.type==='result'){
    const reply=replies.current.get(value.id);if(reply){clearTimeout(reply.timer);replies.current.delete(value.id);if(value.ok)reply.resolve();else reply.reject(new Error(value.error||''));}
    if(value.id===pending.current){setBusy(false);if(value.ok){setDraft('');setFiles([]);setCompose(false);}else setError(value.error||'');}
  }
  else if(value.type==='fixture-ui'){if(value.action==='pet-hover')setHover(!!value.hover);else if(value.action==='double-click')pet.current?.dispatchEvent(new MouseEvent('dblclick',{bubbles:true}));else if(value.action==='reduced'){window.matchMedia=query=>{const result=originalMatchMedia(query);if(query==='(prefers-reduced-motion:reduce)')Object.defineProperty(result,'matches',{value:!!value.enabled});return result;};}else if(value.action==='drag-loss')pet.current?.dispatchEvent(new PointerEvent('lostpointercapture',{bubbles:true}));else if(value.action==='drag-cancel')pet.current?.dispatchEvent(new PointerEvent('pointercancel',{bubbles:true}));else if(value.action==='new'){setCompose(true);setCollapsed(false);bridge.focus();}else if(value.action==='text')setDraft(value.text||'');else if(value.action==='outside')pet.current?.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,button:2}));else if(value.action==='hover')setControls(!!value.hover);else if(value.action==='collapse')foldRef.current();else if(value.action==='request'){setRequest(latest?.notifications?.items.find((item:any)=>item.id===value.id)||null);}}
 };subscribers.add(listener);if(latest)setState(latest);return()=>{subscribers.delete(listener);};},[]);
 useEffect(()=>{if(!state?.image)return;const image=new Image();image.onload=()=>{const canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;const context=canvas.getContext('2d')!;context.drawImage(image,0,0);pixels.current=context.getImageData(0,0,canvas.width,canvas.height).data;};image.src='data:image/png;base64,'+state.image;},[state?.image]);
 useEffect(()=>{let timer:number;const measure=document.createElement('canvas').getContext('2d'),mirror=document.createElement('div');mirror.setAttribute('aria-hidden','true');mirror.style.visibility='hidden';document.body.append(mirror);const tick=()=>{
  const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
  const rect=pet.current?.getBoundingClientRect(),active=document.activeElement,editor=(active instanceof HTMLInputElement||active instanceof HTMLTextAreaElement)&&active.closest('.composer,.follow-up')?active:null;let gaze=null;
  // Directional rows follow an active editor caret, not the user's desktop mouse.
  if(state?.version===2&&['idle','running','waving'].includes(pose)&&!transient&&rect&&editor&&document.hasFocus()&&measure){
   const point=editorCaret(editor,measure,mirror);gaze=gazeCell(point.x-(rect.left+rect.width/2),point.y-(rect.top+rect.height/2));
  }
  setCell(old=>{const next=clock.current.sample(pose,performance.now(),gaze,reduced);return old.row===next.row&&old.column===next.column?old:next;});timer=requestAnimationFrame(tick);
 };timer=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(timer);mirror.remove();};},[pose,state?.version,transient]);
 useLayoutEffect(()=>{
  if(!shell.current)return;
  const report=()=>{const rectangles=Array.from(shell.current!.querySelectorAll<HTMLElement>('[data-hit],[data-hover]')).filter(element=>element.offsetWidth&&element.offsetHeight).map(element=>{const rect=element.getBoundingClientRect();const result:any={x:rect.x,y:rect.y,width:rect.width,height:rect.height,hover:element.hasAttribute('data-hover')};if(result.hover&&pet.current){const mascot=pet.current.getBoundingClientRect();result.x=mascot.x;result.y=mascot.y;result.width=mascot.width;result.height=mascot.height+50;}if(element===pet.current && pixels.current){const bytes=new Uint8Array(192*208/8),data=pixels.current;for(let y=0;y<208;y++)for(let x=0;x<192;x++){const i=y*192+x,alpha=data[((cell.row*208+y)*1536+cell.column*192+x)*4+3];if(alpha>8)bytes[i>>3]|=1<<(i&7);}result.mask=btoa(String.fromCharCode(...bytes));}return result;});bridge.hitZones(rectangles);bridge.resize({height:shell.current!.getBoundingClientRect().height,petTop:pet.current?.getBoundingClientRect().top??12});};
  const observer=new ResizeObserver(report);observer.observe(shell.current);report();return()=>observer.disconnect();
 },[state,cell,compose,collapsed,menu,request,controls,above,panelOffsetX,call]);
 useEffect(()=>{if(!state?.id)return;const ready=()=>requestAnimationFrame(()=>bridge.emit({type:'shown',id:state.id}));if(!state.image){ready();return;}const image=new Image();image.onload=ready;image.onerror=()=>bridge.emit({type:'shown',id:state.id});image.src='data:image/png;base64,'+state.image;},[state?.id]);
 useEffect(()=>{if(compose){requestAnimationFrame(()=>input.current?.focus());}},[compose]);
 const liveRequest=request?items.find((item:any)=>item.id===request.id&&item.token===request.token&&item.request?.key===request.request?.key):null;
 useEffect(()=>{if(request&&!liveRequest)setRequest(null);},[request,liveRequest]);
 useEffect(()=>{const end=()=>endDragRef.current(),escape=(event:KeyboardEvent)=>{if(event.key==='Escape')end();};window.addEventListener('pointerup',end,true);window.addEventListener('pointercancel',end,true);window.addEventListener('blur',end);window.addEventListener('keydown',escape,true);return()=>{end();window.removeEventListener('pointerup',end,true);window.removeEventListener('pointercancel',end,true);window.removeEventListener('blur',end);window.removeEventListener('keydown',escape,true);};},[]);
 useEffect(()=>{if(!compose)return;const outside=(event:PointerEvent)=>{if(!(event.target instanceof Element)||!event.target.closest('.composer,.attachments,.status,.composer-error'))dismissRef.current();};document.addEventListener('pointerdown',outside,true);return()=>document.removeEventListener('pointerdown',outside,true);},[compose]);
 useEffect(()=>{(window as any).__petInspect=()=>({pose,cell,above,controls,panelOffsetX,toolbarAppearance:document.querySelector('.toolbar')?{width:document.querySelector('.toolbar')!.getBoundingClientRect().width,height:document.querySelector('.toolbar')!.getBoundingClientRect().height}:null,replyStyle:document.querySelector('.notice-actions .round')?{color:getComputedStyle(document.querySelector('.notice-actions .round')!).color,background:getComputedStyle(document.querySelector('.notice-actions .round')!).backgroundColor,iconWidth:document.querySelector('.notice-actions .round svg')?.getBoundingClientRect().width}:null,callPhase:call.phase,callVisible:!!document.querySelector('.call-panel'),callTitle:call.title,callSaid:call.said,rendererDragging:dragging.current,toolbarButtonCount:document.querySelectorAll('.toolbar button').length,collapsed,composerVisible:compose&&!collapsed,composerText:draft,composerError:document.querySelector('.composer-error')?.textContent||'',noticesVisible:!collapsed&&items.length>0,petBounds:pet.current?.getBoundingClientRect().toJSON(),toolbarBounds:document.querySelector('.toolbar')?.getBoundingClientRect().toJSON(),noticeBounds:document.querySelector('.notice')?.getBoundingClientRect().toJSON(),noticePreview:document.querySelector('.notice-copy')?.textContent,noticeTitleBounds:document.querySelector('.notice-copy strong')?.getBoundingClientRect().toJSON(),noticeSubtitleBounds:document.querySelector('.notice-subtitle')?.getBoundingClientRect().toJSON(),noticeSubtitle:document.querySelector('.notice-subtitle')?.textContent,noticeProgress:document.querySelector('.notice-subtitle')?.classList.contains('is-active'),requestVisible:!!document.querySelector('.request'),replyVisible:!!document.querySelector('.follow-up')});},[pose,cell,above,controls,panelOffsetX,collapsed,compose,draft,items.length,call]);
 const openComposer=()=>{setCompose(true);setCollapsed(false);setError('');bridge.focus();};
 const fold=()=>{if(!collapsed){action({type:'voice-cancel'});setVoice('idle');}setCollapsed(!collapsed);setCompose(false);setRequest(null);setMenu(false);};foldRef.current=fold;
 const send=()=>{if(!draft.trim() || busy)return;setBusy(true);setError('');pending.current=action({type:'send-message',text:draft,files});};
 if(!state)return <div className="shell" ref={shell}/>;
 return <div className={'shell '+(above?'above ':'')+(state.theme==='dark'?'dark':'')} ref={shell} style={{'--panel-offset-x':panelOffsetX+'px'} as React.CSSProperties}>
 <div className="mascot-group" data-hover>
  <div ref={pet} data-hit className="pet" aria-label={t('悬浮宠物','Floating pet')} style={{width:size,height:size*208/192,backgroundImage:'url(data:image/png;base64,'+state.image+')',backgroundSize:`${size*8}px ${size*208/192*(state.version===2?11:9)}px`,backgroundPosition:`${-cell.column*size}px ${-cell.row*size*208/192}px`}} onPointerEnter={()=>setHover(true)} onPointerLeave={()=>setHover(false)} onPointerDown={event=>{if(event.button!==0||dragging.current)return;dragging.current=true;dragToken.current=crypto.randomUUID();captureId.current=event.pointerId;try{event.currentTarget.setPointerCapture(event.pointerId);bridge.drag(true,dragToken.current);}catch{endDrag();}}} onPointerMove={event=>{if(dragging.current&&!(event.buttons&1))endDrag();}} onPointerUp={endDrag} onPointerCancel={endDrag} onLostPointerCapture={endDrag} onContextMenu={event=>{endDrag();event.preventDefault();setMenu(!menu);}}/>
  {!compose || collapsed?<div className="toolbar-slot"><div className={'toolbar '+(controls?'expanded':'compact')} style={{width:controls?(items.length?120:80):17}} data-hit>{controls?<><button title={t('新对话','New conversation')} onClick={openComposer}><Icon name="new"/></button><button title={call.active?t('结束通话','End call'):t('语音通话','Voice call')} className={call.active?'call-active':''} onClick={()=>action({type:'call-toggle'})}><Icon name="voice"/></button>{items.length?<button title={t('折叠/展开对话','Collapse/expand conversations')} onClick={fold}><span className={above&&!collapsed?'chevron-up':''}><Icon name={collapsed?'bell':'down'}/></span>{collapsed?<span className="badge">{items.length}</span>:null}</button>:null}</>:<span className="compact-grip"/>}</div></div>:null}
  {menu?<div className="menu" data-hit><button onClick={()=>{setCompose(true);setCollapsed(false);setMenu(false);bridge.focus();action({type:'voice-toggle'});}}>{t('语音转文字','Voice dictation')}</button><button onClick={()=>{bridge.emit({type:'settings'});setMenu(false);}}>{t('宠物设置','Pet settings')}</button><button onClick={()=>bridge.emit({type:'config',value:{desktop:false}})}>{t('返回页内显示','Show inside DSH')}</button><button onClick={()=>bridge.emit({type:'config',value:{visible:false}})}>{t('收起宠物','Hide pet')}</button></div>:null}
  {call.active||call.error?<section className={'call-panel '+(call.phase==='speaking'?'is-speaking':'')} data-hit aria-label={t('语音通话','Voice call')}><div className="call-header"><span className={'call-dot '+(call.muted?'is-muted':'')}/><strong>{t('语音通话','Voice call')}</strong><span className="call-phase">{{off:t('已结束','Ended'),starting:t('正在准备','Preparing'),listening:t('正在听','Listening'),recognizing:t('正在识别','Recognizing'),thinking:t('正在回答','Answering'),working:t('任务处理中','Working'),'preparing-audio':t('准备语音','Preparing audio'),speaking:t('正在说','Speaking'),muted:t('已暂停收音','Mic paused'),error:t('暂不可用','Unavailable')}[call.phase]}</span>{call.active?<><button className="round" title={call.muted?t('恢复收音','Resume mic'):t('暂停收音','Pause mic')} aria-pressed={call.muted} onClick={()=>action({type:'call-mute'})}><Icon name={call.muted?'muted':'mic'}/></button><button className="round call-hangup" title={t('挂断，后台任务继续','Hang up; keep task running')} onClick={()=>action({type:'call-end'})}><Icon name="hangup"/></button></>:<button className="round" title={t('关闭提示','Dismiss')} onClick={()=>action({type:'call-end'})}><Icon name="close"/></button>}</div><div className="call-target">{call.title||t('第一句话后创建对话','A conversation starts on your first message')}</div>{call.heard?<p className="call-heard">{call.heard}</p>:<p className="call-hint">{t('说完后稍作停顿，消息会自动发送。','Pause after speaking to send automatically.')}</p>}{call.said?<p className="call-said">{call.said}</p>:null}{call.active?<div className="call-level" aria-hidden="true"><span style={{width:(Math.max(.02,call.level)*100)+'%'}}/></div>:null}{call.error?<p className="call-error" role="alert">{call.error}</p>:null}</section>:null}
  {!collapsed&&compose?<><form className="composer" data-hit onSubmit={event=>{event.preventDefault();send();}}><button type="button" className="round" title={t('添加文件引用','Add file references')} onClick={async()=>setFiles(await (bridge as any).chooseFiles())}><Icon name="plus"/></button><input ref={input} value={draft} maxLength={10000} placeholder={t('开始新聊天','Start a new chat')} aria-label={t('消息','Message')} onFocus={()=>bridge.focus()} onChange={event=>setDraft(event.target.value)} onKeyDown={event=>{if(event.key==='Escape'){setCompose(false);action({type:'voice-cancel'});}else if(event.key==='Enter'&&(event.ctrlKey||event.metaKey)&&!event.nativeEvent.isComposing){event.preventDefault();send();}}}/><button type="submit" className="round send" disabled={!draft.trim()||busy} title={t('发送','Send')}><Icon name="send"/></button></form>{files.length?<div className="attachments">{files.map(file=><span className="attachment" key={file}>{file.split(/[\\/]/).pop()}</span>)}</div>:null}{error?<div className="composer-error">{error}</div>:null}{voice!=='idle'?<div className="status" data-hit><button onClick={()=>action({type:'voice-toggle'})}>{voice==='recording'?t('正在录音 · 点击结束','Recording · click to finish'):t('正在转写…','Transcribing…')}</button></div>:null}</>:null}
 </div>
  {!collapsed&&items.length?<div className="stack">{items.slice(0,4).map((item:any)=><NoticeCard key={item.id+':'+item.token} item={item} t={t} command={answered} showRequest={()=>setRequest(item)} drafts={replyDrafts.current}/>)}</div>:null}
  {liveRequest?<div className="request" data-hit><RequestForm key={liveRequest.request.key+JSON.stringify(liveRequest.request.questions)} item={liveRequest} language={state.language} command={async command=>{await answered(command);setRequest(null);}}/><button onClick={()=>setRequest(null)}>{t('关闭','Close')}</button></div>:null}
 </div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
