/** 以用户提供的 Codex 设置截图为基准；在宿主内优先采用 DSH 主题变量。 */
export const styles = `
.dcp{--pet-bg:var(--dsw-alias-bg-base,#181818);--pet-card:var(--dsw-alias-bg-layer-2,var(--dsw-alias-bg-base,#242424));--pet-line:var(--dsw-alias-border-l2,#343434);--pet-text:var(--dsw-alias-label-primary,#d7d7d7);--pet-muted:var(--dsw-alias-label-secondary,#929292);font-family:Arial,"Microsoft YaHei",sans-serif;color:var(--pet-text);font-size:13px;line-height:1.45;color-scheme:inherit}
.dcp *{box-sizing:border-box}.dcp button,.dcp input,.dcp textarea{font:inherit}.dcp button{border:0;color:var(--pet-text);background:transparent;cursor:pointer}.dcp button:disabled{opacity:.4;cursor:default}.dcp button:focus-visible,.dcp input:focus-visible,.dcp textarea:focus-visible{outline:2px solid #9bc8ff;outline-offset:3px}.dcp button:hover:not(:disabled){background:color-mix(in srgb,var(--pet-text) 8%,transparent)}
.dcp-page{max-width:768px;margin:0 auto;padding:0 0 32px}.dcp-page h1{font-size:24px;font-weight:600;margin:0 0 32px;line-height:1.3}.dcp-page h2{font-size:14px;font-weight:600;margin:0}.dcp-head{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;margin-bottom:12px}.dcp-sub{color:var(--pet-muted);margin:4px 0 0;font-size:12px}.dcp-actions{display:flex;align-items:center;gap:8px}.dcp .dcp-button{border-radius:7px;padding:5px 9px;background:color-mix(in srgb,var(--pet-text) 3%,transparent);white-space:nowrap;font-weight:500}.dcp .dcp-icon{display:inline-flex;align-items:center;justify-content:center;padding:6px;border-radius:6px}.dcp svg{width:16px;height:16px;flex-shrink:0}
.dcp-card{border:1px solid var(--pet-line);border-radius:16px;background:var(--pet-card);overflow:hidden;padding:0 16px}.dcp-row{display:flex;align-items:center;gap:18px;min-height:88px;border-bottom:1px solid var(--pet-line)}.dcp-preview{width:58px;flex-shrink:0;display:flex;justify-content:center;align-items:center}.dcp-info{flex:1;min-width:0}.dcp-name{font-size:13px;font-weight:600;margin-bottom:3px}.dcp-description{font-size:12px;color:var(--pet-muted);overflow-wrap:anywhere}.dcp-folder{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:12px 0}.dcp-path{font-family:Consolas,monospace;font-size:11px;color:var(--pet-muted);overflow-wrap:anywhere}.dcp .dcp-folder-button{display:flex;align-items:center;gap:6px;color:var(--pet-muted);white-space:nowrap}.dcp-appearance{margin-top:48px}.dcp-size{margin-top:14px;min-height:62px;display:flex;align-items:center;justify-content:space-between;padding:12px 16px}.dcp-size label{font-weight:600}.dcp-size input{width:160px;height:2px;accent-color:white;cursor:pointer}.dcp-size small{display:block;font-size:12px;color:var(--pet-muted);font-weight:400;margin-top:2px}.dcp-note{margin:12px 0;color:var(--pet-muted);font-size:12px}.dcp-error{padding:12px;border:1px solid #845344;border-radius:8px;color:#edb7a3;margin:12px 0;font-size:12px}.dcp-empty{padding:32px 0;text-align:center;color:var(--pet-muted)}
.dcp-floating{position:fixed;z-index:2147483000;pointer-events:none}.dcp-pet-button{display:block!important;padding:0!important;background:transparent!important;touch-action:none;cursor:grab!important;pointer-events:auto;user-select:none;-webkit-user-select:none}.dcp-pet-button:active{cursor:grabbing!important}.dcp-sprite{background-repeat:no-repeat;pointer-events:none;flex-shrink:0}.dcp-bubble{position:absolute;bottom:calc(100% + 16px);right:0;min-width:160px;max-width:240px;width:max-content;padding:10px 16px!important;border:1px solid var(--pet-line)!important;border-radius:28px!important;background:var(--pet-card)!important;text-align:left;box-shadow:0 2px 12px #0002;pointer-events:auto}.dcp-bubble strong{display:block;max-width:200px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:12px}.dcp-bubble span{display:block;font-size:12px;color:var(--pet-muted)}.dcp-menu{position:absolute;right:0;bottom:100%;width:160px;padding:6px;border:1px solid var(--pet-line);background:var(--pet-card);border-radius:10px;pointer-events:auto;box-shadow:0 8px 32px #0004}.dcp-menu button{display:block;width:100%;text-align:left;padding:8px;border-radius:5px}.dcp-menu hr{border:0;border-top:1px solid var(--pet-line);margin:5px}
.dcp-dialog{color:var(--pet-text);background:var(--pet-card);border:1px solid var(--pet-line);border-radius:16px;width:min(480px,calc(100vw - 32px));padding:24px}.dcp-dialog::backdrop{background:#0008}.dcp-dialog h2{font-size:19px;margin:0 0 12px}.dcp-dialog textarea{display:block;resize:vertical;width:100%;min-height:120px;color:var(--pet-text);background:var(--pet-bg);border:1px solid var(--pet-line);border-radius:8px;padding:12px;margin:16px 0}.dcp-dialog footer{display:flex;justify-content:flex-end;gap:8px}.dcp-dialog .dcp-primary{background:#e6e6e6!important;color:#222!important}.dcp-creation{border-top:1px solid var(--pet-line);padding-top:12px;margin-top:12px}
.dcp-light{--pet-bg:#fff;--pet-card:#f7f7f7;--pet-line:#e4e4e4;--pet-text:#252525;--pet-muted:#727272;color-scheme:light}.dcp-light.dcp-light .dcp-size input{accent-color:#222}
.dcp-size input{-webkit-appearance:none;appearance:none;background:var(--pet-line);height:2px}.dcp-size input::-webkit-slider-thumb{-webkit-appearance:none;width:20px;height:20px;border-radius:50%;background:var(--pet-text)}
@media(max-width:600px){.dcp-page h1{font-size:22px;margin-bottom:24px}.dcp-head{flex-wrap:wrap;gap:10px}.dcp-row{min-height:86px;gap:8px}.dcp-preview{width:44px}.dcp-description{font-size:11px}.dcp-card{padding:0 12px}.dcp-folder{align-items:flex-start}.dcp-folder-button{font-size:11px!important}.dcp-size{padding:12px}.dcp-size input{width:130px}.dcp-appearance{margin-top:32px}}
.dcp-size input[type=checkbox]{appearance:none;-webkit-appearance:none;position:relative;width:36px;height:20px;flex-shrink:0;border:0;border-radius:12px;background:#aeb4bf;cursor:pointer}.dcp-size input[type=checkbox]::after{content:'';position:absolute;width:16px;height:16px;left:2px;top:2px;border-radius:50%;background:white;transition:transform .15s}.dcp-size input[type=checkbox]:checked{background:#4f72ef}.dcp-size input[type=checkbox]:checked::after{transform:translateX(16px)}.dcp-size input[type=checkbox]:focus-visible{outline:2px solid #4f8fff;outline-offset:3px}
@media(prefers-reduced-motion:reduce){.dcp *{animation:none!important;transition:none!important}}
`;
